### ISSUE TITLE
Should we display the time of messages as well, not just the date?

### ISSUE THREAD

**Issue by joulev** [rafaelalmeidatk/nextjs-forum#16]
https://github.com/rafaelalmeidatk/nextjs-forum/blob/202ef7fc1124710383a1d8ecfb02b0085c320d9e/apps/web/utils/datetime.ts#L3-L7

Right now the timestamps in long form are displayed as dates only, e.g. "Jun 11". It seems this is an intentional decision, but shouldn't the time be displayed as well, e.g. "Jun 11 at 13:45"?

**Comment by rafaelalmeidatk** [comment]
Yeah this was intended, but I don't remember why  :sweat_smile: 
I think we should just copy Discord: `05/21/2023 7:33 AM`

(ops sorry wrong button)
