### ISSUE TITLE
Use Yarn V3

### ISSUE THREAD

**Issue by RiskyMH** [rafaelalmeidatk/nextjs-forum#59]
As Yarn v1 is depreciated now, I think this project should update to v3 (aka [yarn berry](https://github.com/yarnpkg/berry)) to get the new features. This also comes with better workspace tools (like in packages you can do `"@nextjs-forum/db": "workspace:^"`).

https://yarnpkg.com/getting-started/migration

**Comment by rafaelalmeidatk** [comment]
Tbh I am thinking about just using pnpm instead: https://pnpm.io/

**Comment by landsman** [comment]
safe time and use goold old npm 🙏

**Comment by RiskyMH** [comment]
used pnpm instead!
